INSERT INTO books (isbn, title, author) VALUES (1, 'To Kill a Mockingbird', 'Harper Lee');
INSERT INTO books (isbn, title, author) VALUES (2, '1984', 'George Orwell');
INSERT INTO books (isbn, title, author) VALUES (3, 'The Great Gatsby', 'F. Scott Fitzgerald');
INSERT INTO books (isbn, title, author) VALUES (4, 'The Catcher in the Rye', 'J.D. Salinger');
INSERT INTO books (isbn, title, author) VALUES (5, 'The Hobbit', 'J.R.R. Tolkien');
INSERT INTO books (isbn, title, author) VALUES (6, 'Fahrenheit 451', 'Ray Bradbury');
INSERT INTO books (isbn, title, author) VALUES (7, 'Moby-Dick', 'Herman Melville');
INSERT INTO books (isbn, title, author) VALUES (8, 'Pride and Prejudice', 'Jane Austen');
INSERT INTO books (isbn, title, author) VALUES (9, 'War and Peace', 'Leo Tolstoy');
INSERT INTO books (isbn, title, author) VALUES (10, 'Crime and Punishment', 'Fyodor Dostoevsky');
INSERT INTO books (isbn, title, author) VALUES (11, 'The Brothers Karamazov', 'Fyodor Dostoevsky');
INSERT INTO books (isbn, title, author) VALUES (12, 'Anna Karenina', 'Leo Tolstoy');
INSERT INTO books (isbn, title, author) VALUES (13, 'Brave New World', 'Aldous Huxley');
INSERT INTO books (isbn, title, author) VALUES (14, 'The Lord of the Rings', 'J.R.R. Tolkien');
INSERT INTO books (isbn, title, author) VALUES (15, 'Gone with the Wind', 'Margaret Mitchell');
INSERT INTO books (isbn, title, author) VALUES (16, 'Jane Eyre', 'Charlotte Brontë');
INSERT INTO books (isbn, title, author) VALUES (17, 'Wuthering Heights', 'Emily Brontë');
INSERT INTO books (isbn, title, author) VALUES (18, 'The Odyssey', 'Homer');
INSERT INTO books (isbn, title, author) VALUES (19, 'Ulysses', 'James Joyce');
INSERT INTO books (isbn, title, author) VALUES (20, 'One Hundred Years of Solitude', 'Gabriel García Márquez');
INSERT INTO books (isbn, title, author) VALUES (21, 'The Iliad', 'Homer');
INSERT INTO books (isbn, title, author) VALUES (22, 'Don Quixote', 'Miguel de Cervantes');
INSERT INTO books (isbn, title, author) VALUES (23, 'The Divine Comedy', 'Dante Alighieri');
INSERT INTO books (isbn, title, author) VALUES (24, 'Madame Bovary', 'Gustave Flaubert');
INSERT INTO books (isbn, title, author) VALUES (25, 'The Picture of Dorian Gray', 'Oscar Wilde');
INSERT INTO books (isbn, title, author) VALUES (26, 'The Metamorphosis', 'Franz Kafka');
INSERT INTO books (isbn, title, author) VALUES (27, 'The Stranger', 'Albert Camus');
INSERT INTO books (isbn, title, author) VALUES (28, 'The Trial', 'Franz Kafka');
INSERT INTO books (isbn, title, author) VALUES (29, 'The Grapes of Wrath', 'John Steinbeck');
INSERT INTO books (isbn, title, author) VALUES (30, 'East of Eden', 'John Steinbeck');
INSERT INTO books (isbn, title, author) VALUES (31, 'The Sun Also Rises', 'Ernest Hemingway');
INSERT INTO books (isbn, title, author) VALUES (32, 'The Old Man and the Sea', 'Ernest Hemingway');
INSERT INTO books (isbn, title, author) VALUES (33, 'Of Mice and Men', 'John Steinbeck');
INSERT INTO books (isbn, title, author) VALUES (34, 'Catch-22', 'Joseph Heller');
INSERT INTO books (isbn, title, author) VALUES (35, 'Slaughterhouse-Five', 'Kurt Vonnegut');
INSERT INTO books (isbn, title, author) VALUES (36, 'Beloved', 'Toni Morrison');
INSERT INTO books (isbn, title, author) VALUES (37, 'Invisible Man', 'Ralph Ellison');
INSERT INTO books (isbn, title, author) VALUES (38, 'The Sound and the Fury', 'William Faulkner');
INSERT INTO books (isbn, title, author) VALUES (39, 'Light in August', 'William Faulkner');
INSERT INTO books (isbn, title, author) VALUES (40, 'As I Lay Dying', 'William Faulkner');
INSERT INTO books (isbn, title, author) VALUES (41, 'The Scarlet Letter', 'Nathaniel Hawthorne');
INSERT INTO books (isbn, title, author) VALUES (42, 'Frankenstein', 'Mary Shelley');
INSERT INTO books (isbn, title, author) VALUES (43, 'Dracula', 'Bram Stoker');
INSERT INTO books (isbn, title, author) VALUES (44, 'The Count of Monte Cristo', 'Alexandre Dumas');
INSERT INTO books (isbn, title, author) VALUES (45, 'The Three Musketeers', 'Alexandre Dumas');
INSERT INTO books (isbn, title, author) VALUES (46, 'Les Misérables', 'Victor Hugo');
INSERT INTO books (isbn, title, author) VALUES (47, 'The Hunchback of Notre-Dame', 'Victor Hugo');
INSERT INTO books (isbn, title, author) VALUES (48, 'A Tale of Two Cities', 'Charles Dickens');
INSERT INTO books (isbn, title, author) VALUES (49, 'Great Expectations', 'Charles Dickens');
INSERT INTO books (isbn, title, author) VALUES (50, 'David Copperfield', 'Charles Dickens');
